//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidEdge.Spy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolidEdge.Spy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterActiveDocumentChange(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterActiveDocumentChangeFormat {
            get {
                return ResourceManager.GetString("AfterActiveDocumentChangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterCommandRun(theCommandID = {0}).
        /// </summary>
        internal static string AfterCommandRunFormat {
            get {
                return ResourceManager.GetString("AfterCommandRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterDocumentOpen(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterDocumentOpenFormat {
            get {
                return ResourceManager.GetString("AfterDocumentOpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterDocumentPrint(theDocument = &apos;{0}&apos;, hDC = &apos;{1}&apos;, ModelToDC = &apos;{2}&apos;, Rect = &apos;{3}&apos;).
        /// </summary>
        internal static string AfterDocumentPrintFormat {
            get {
                return ResourceManager.GetString("AfterDocumentPrintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterDocumentSave(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterDocumentSaveFormat {
            get {
                return ResourceManager.GetString("AfterDocumentSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterEnvironmentActivate(theEnvironment = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterEnvironmentActivateFormat {
            get {
                return ResourceManager.GetString("AfterEnvironmentActivateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterNewDocumentOpen(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterNewDocumentOpenFormat {
            get {
                return ResourceManager.GetString("AfterNewDocumentOpenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterNewWindow(theWindow = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterNewWindowFormat {
            get {
                return ResourceManager.GetString("AfterNewWindowFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfterWindowActivate(theWindow = &apos;{0}&apos;).
        /// </summary>
        internal static string AfterWindowActivateFormat {
            get {
                return ResourceManager.GetString("AfterWindowActivateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alias_16x16 {
            get {
                object obj = ResourceManager.GetObject("Alias_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowBack_16x16 {
            get {
                object obj = ResourceManager.GetObject("ArrowBack_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowForward_16x16 {
            get {
                object obj = ResourceManager.GetObject("ArrowForward_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeCommandRun(theCommandID = {0}).
        /// </summary>
        internal static string BeforeCommandRunFormat {
            get {
                return ResourceManager.GetString("BeforeCommandRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeDocumentClose(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string BeforeDocumentCloseFormat {
            get {
                return ResourceManager.GetString("BeforeDocumentCloseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeDocumentPrint(theDocument = &apos;{0}&apos;, hDC = &apos;{1}&apos;, ModelToDC = &apos;{2}&apos;, Rect = &apos;{3}&apos;).
        /// </summary>
        internal static string BeforeDocumentPrintFormat {
            get {
                return ResourceManager.GetString("BeforeDocumentPrintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeDocumentSave(theDocument = &apos;{0}&apos;).
        /// </summary>
        internal static string BeforeDocumentSaveFormat {
            get {
                return ResourceManager.GetString("BeforeDocumentSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeEnvironmentDeactivate(theEnvironment = &apos;{0}&apos;).
        /// </summary>
        internal static string BeforeEnvironmentDeactivateFormat {
            get {
                return ResourceManager.GetString("BeforeEnvironmentDeactivateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeQuit().
        /// </summary>
        internal static string BeforeQuitFormat {
            get {
                return ResourceManager.GetString("BeforeQuitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeforeWindowDeactivate(theWindow = &apos;{0}&apos;).
        /// </summary>
        internal static string BeforeWindowDeactivateFormat {
            get {
                return ResourceManager.GetString("BeforeWindowDeactivateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Class_16x16 {
            get {
                object obj = ResourceManager.GetObject("Class_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClearSearch_16x16 {
            get {
                object obj = ResourceManager.GetObject("ClearSearch_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgespy.codeplex.com/discussions.
        /// </summary>
        internal static string CodePlexDiscussionsUrl {
            get {
                return ResourceManager.GetString("CodePlexDiscussionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgespy.codeplex.com/documentation.
        /// </summary>
        internal static string CodePlexDocumentationurl {
            get {
                return ResourceManager.GetString("CodePlexDocumentationurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://solidedgespy.codeplex.com.
        /// </summary>
        internal static string CodePlexUrl {
            get {
                return ResourceManager.GetString("CodePlexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse_16x16 {
            get {
                object obj = ResourceManager.GetObject("Collapse_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommandBrowser_16x16 {
            get {
                object obj = ResourceManager.GetObject("CommandBrowser_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComTreeItemBlue_16x16 {
            get {
                object obj = ResourceManager.GetObject("ComTreeItemBlue_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComTreeItemGray_16x16 {
            get {
                object obj = ResourceManager.GetObject("ComTreeItemGray_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComTreeItemsBlue_16x16 {
            get {
                object obj = ResourceManager.GetObject("ComTreeItemsBlue_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComTreeItemsGray_16x16 {
            get {
                object obj = ResourceManager.GetObject("ComTreeItemsGray_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_16x16 {
            get {
                object obj = ResourceManager.GetObject("Constant_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enum_16x16 {
            get {
                object obj = ResourceManager.GetObject("Enum_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Erase_16x16 {
            get {
                object obj = ResourceManager.GetObject("Erase_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Event_16x16 {
            get {
                object obj = ResourceManager.GetObject("Event_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand_16x16 {
            get {
                object obj = ResourceManager.GetObject("Expand_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Find_16x16 {
            get {
                object obj = ResourceManager.GetObject("Find_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderClosed_16x16 {
            get {
                object obj = ResourceManager.GetObject("FolderClosed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen_16x16 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/SolidEdgeCommunity/Samples.
        /// </summary>
        internal static string GitHubSamples {
            get {
                return ResourceManager.GetString("GitHubSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/solidedgecommunity.
        /// </summary>
        internal static string GitHubSolidEdgeCommunityUrl {
            get {
                return ResourceManager.GetString("GitHubSolidEdgeCommunityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interface_16x16 {
            get {
                object obj = ResourceManager.GetObject("Interface_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Library_16x16 {
            get {
                object obj = ResourceManager.GetObject("Library_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Method_16x16 {
            get {
                object obj = ResourceManager.GetObject("Method_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Namespace_16x16 {
            get {
                object obj = ResourceManager.GetObject("Namespace_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nuget.org/packages/Interop.SolidEdge.
        /// </summary>
        internal static string NuGetInteropSolidEdge {
            get {
                return ResourceManager.GetString("NuGetInteropSolidEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nuget.org/packages/SolidEdge.Community.
        /// </summary>
        internal static string NuGetSolidEdgeCommunity {
            get {
                return ResourceManager.GetString("NuGetSolidEdgeCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.nuget.org/packages/SolidEdge.Community.Reader.
        /// </summary>
        internal static string NuGetSolidEdgeCommunityReader {
            get {
                return ResourceManager.GetString("NuGetSolidEdgeCommunityReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Parameter_16x16 {
            get {
                object obj = ResourceManager.GetObject("Parameter_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProcessModules_16x16 {
            get {
                object obj = ResourceManager.GetObject("ProcessModules_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Property_16x16 {
            get {
                object obj = ResourceManager.GetObject("Property_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sespy_128x128 {
            get {
                object obj = ResourceManager.GetObject("sespy_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start_16x16 {
            get {
                object obj = ResourceManager.GetObject("Start_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Structure_16x16 {
            get {
                object obj = ResourceManager.GetObject("Structure_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
